baseurl: https://sergiolopezolvera.netlify.app/
title: Sergio Lopez Olvera | Data Scientist
author: Serrgio Lopez Olvera
canonifyurls: yes
languagecode: en
theme: hugo-lithium
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: Sergio López Olvera
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Portfolio
      url: /
      weight: 1
    - name: Resume
      url: /resume/
      weight: 2
    - name: GitHub
      url: https://github.com/sergiolopezolvera
      weight: 3
    - name: LinkedIn
      url: https://linkedin.com/in/sergiolopezolvera
      weight: 4

